version: "3.9"

services:
  dogwalk:
    build: .
    container_name: dog-walk-planner
    ports:
      - "6969:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./secrets:/app/secrets
      - ./config:/app/config
      - /opt/apps/dog-walk-planner/secrets.toml:/app/.streamlit/secrets.toml:ro
      - /opt/apps/dog-walk-planner/.env:/app/.env:ro
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
