version: "3.9"

services:
  dogwalk:
    build: .
    container_name: dog-walk-planner
    ports:
      - "6969:3000"
    volumes:
      - ./data:/app/data
      - /opt/apps/dog-walk-planner/.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
